#!/bin/bash

. /etc/productConf/mc.conf 2> /dev/null

if [[ ! -f "${MinecraftFolder}" ]]; then
    mkdir -p "${MinecraftFolder}"
    chmod 777 "${MinecraftFolder}"
fi

cd "${MinecraftFolder}"

wget "https://maven.minecraftforge.net/net/minecraftforge/forge/${ForgeVersion}/forge-${ForgeVersion}-installer.jar"
java -jar "forge-${ForgeVersion}-installer.jar" --installServer
rm "forge-${ForgeVersion}-installer.jar"
echo -n "$ForgeVersion" > "./forge.version"

mv /tmp/run.sh .
./run.sh

sed -i "s/false/true/" "./eula.txt"

mv /tmp/server.properties .

chmod 777 server.properties
rm -rf "${MinecraftFolder}/logs"
mkdir "${MinecraftFolder}/logs"
chmod 777 "${MinecraftFolder}/logs"

systemctl enable minecraft-server-api.service
systemctl start minecraft-server-api.service