#!/bin/bash

FOLDERS=("/usr/share/server/minecraft" "/etc/productConf" "/var/log/product")

for folder in ${FOLDERS[@]}; do
    if [[ ! -d $folder ]]; then
        echo "Creating ${folder}"
        mkdir "${folder}"
    fi
done

chmod 777 "/var/log/product"
